set echo on;
spool A_P2.txt
-- WE ARE JOING THE TABLES TITLE_PRINCIPALS,TITLE_BASICS, NAME_BASICS  WITH THE PARAMETERS BASED ON THE PRIMARY KEYS 
-- NOW WE ARE FITERING THE DATA BASED ON STARTYEAR BETWEEN '1926' AND '1930' titletype AS 'movie' FOR MALE 
-- NOW WE COUNT BY GROUP IT BY NCONST THEN PRIMARY NAME AND THEN BY START YEAR 
-- WE SORT THE DATA BY DESC,TB.STARTYEAR ASC,NB.PRIMARYNAME ASC
-- PRINT ONLY THE FIRST ROW
--max for actor 1
SELECT  
        NB.NCONST,
        NB.PRIMARYNAME,
        TB.STARTYEAR,COUNT(*) AS MOVIES_COUNT
FROM sharmac.TITLE_PRINCIPALS  TP
INNER JOIN sharmac.TITLE_BASICS TB 
    ON TP.TCONST = tb.tconst
INNER JOIN  sharmac.NAME_BASICS NB
    ON NB.NCONST = tp.nconst
WHERE (TB.STARTYEAR BETWEEN '1926' AND '1930') AND (tb.titletype='movie') AND (tp.category = 'actor') 
GROUP BY NB.NCONST,NB.PRIMARYNAME , TB.STARTYEAR
ORDER BY COUNT(*) DESC,TB.STARTYEAR ASC,NB.PRIMARYNAME ASC
FETCH FIRST 1 ROWS ONLY;

-- max for actress 2

-- WE ARE JOING THE TABLES TITLE_PRINCIPALS,TITLE_BASICS, NAME_BASICS  WITH THE PARAMETERS BASED ON THE PRIMARY KEYS 
-- NOW WE ARE FITERING THE DATA BASED ON STARTYEAR BETWEEN '1926' AND '1930' titletype AS 'movie' FOR FEMALE
-- NOW WE COUNT BY GROUP IT BY NCONST THEN PRIMARY NAME AND THEN BY START YEAR 
-- WE SORT THE DATA COUNT(*) DESC,TB.STARTYEAR ASC,NB.PRIMARYNAME ASC
-- WE PRINT ONLY THE FIRST ROW

SELECT  NB.NCONST,
        NB.PRIMARYNAME,
        TB.STARTYEAR,COUNT(*) AS MOVIES_COUNT
FROM sharmac.TITLE_PRINCIPALS  TP
INNER JOIN sharmac.TITLE_BASICS TB 
    ON TP.TCONST = tb.tconst
INNER JOIN  sharmac.NAME_BASICS NB
    ON NB.NCONST = tp.nconst
WHERE (TB.STARTYEAR BETWEEN '1926' AND '1930') AND (tb.titletype='movie') AND (tp.category = 'actress') 
GROUP BY NB.NCONST,NB.PRIMARYNAME , TB.STARTYEAR
ORDER BY COUNT(*) DESC,TB.STARTYEAR ASC,NB.PRIMARYNAME ASC
FETCH FIRST 1 ROWS ONLY;


-- male fisrt with 4 movies          

-- WE ARE JOING THE TABLES TITLE_PRINCIPALS,TITLE_BASICS, NAME_BASICS  WITH THE PARAMETERS BASED ON THE PRIMARY KEYS 
-- NOW WE ARE FITERING THE DATA BASED ON STARTYEAR BETWEEN '1926' AND '1930' titletype AS 'movie' FOR MALE 
-- NOW WE COUNT BY GROUP IT BY NCONST THEN PRIMARY NAME AND THEN BY START YEAR 
-- WE SORT THE DATA BY COUNT(*) DESC,TB.STARTYEAR ASC,NB.PRIMARYNAME ASC
-- PRINT ONLY THE FIRST ROW

SELECT  NB.NCONST,
        NB.PRIMARYNAME,
        TB.STARTYEAR,COUNT(*) AS MOVIES_COUNT
FROM sharmac.TITLE_PRINCIPALS  TP
INNER JOIN sharmac.TITLE_BASICS TB 
    ON TP.TCONST = tb.tconst
INNER JOIN  sharmac.NAME_BASICS NB
    ON NB.NCONST = tp.nconst
WHERE (TB.STARTYEAR BETWEEN '1926' AND '1930' ) AND (tb.titletype='movie') AND (tp.category = 'actor') 
GROUP BY NB.NCONST,NB.PRIMARYNAME , TB.STARTYEAR
HAVING COUNT(*)>3
ORDER BY COUNT(*) ASC,TB.STARTYEAR ASC,NB.PRIMARYNAME ASC
FETCH FIRST 1 ROWS ONLY;


-- male last with 4 movies     

-- WE ARE JOING THE TABLES TITLE_PRINCIPALS,TITLE_BASICS, NAME_BASICS  WITH THE PARAMETERS BASED ON THE PRIMARY KEYS 
-- NOW WE ARE FITERING THE DATA BASED ON STARTYEAR BETWEEN '1926' AND '1930' titletype AS 'movie' FOR MALE 
-- NOW WE COUNT BY GROUP IT BY NCONST THEN PRIMARY NAME AND THEN BY START YEAR 
-- SORT BY COUNT(*) ASC,TB.STARTYEAR DESC,NB.PRIMARYNAME desc
-- PRINT ONLY THE FIRST ROW

SELECT  NB.NCONST,
        NB.PRIMARYNAME,
        TB.STARTYEAR,COUNT(*) AS MOVIES_COUNT
FROM sharmac.TITLE_PRINCIPALS  TP
INNER JOIN sharmac.TITLE_BASICS TB 
    ON TP.TCONST = tb.tconst
INNER JOIN  sharmac.NAME_BASICS NB
    ON NB.NCONST = tp.nconst
WHERE (TB.STARTYEAR BETWEEN '1926' AND '1930'  ) AND (tb.titletype='movie') AND (tp.category = 'actor') 
GROUP BY NB.NCONST,NB.PRIMARYNAME , TB.STARTYEAR
HAVING COUNT(*)>3
ORDER BY COUNT(*) ASC,TB.STARTYEAR DESC,NB.PRIMARYNAME desc
FETCH FIRST 1 ROWS ONLY;

-- female first with 4 movies 
-- WE ARE JOING THE TABLES TITLE_PRINCIPALS,TITLE_BASICS, NAME_BASICS  WITH THE PARAMETERS BASED ON THE PRIMARY KEYS 
-- NOW WE ARE FITERING THE DATA BASED ON STARTYEAR BETWEEN '1926' AND '1930' titletype AS 'movie' FOR FEMALE
-- NOW WE COUNT BY GROUP IT BY NCONST THEN PRIMARY NAME AND THEN BY START YEAR 
-- WE SORT THE DATA BYORDER BY COUNT(*) ASC,TB.STARTYEAR ASC,NB.PRIMARYNAME ASC
-- PRINT ONLY THE FIRST 4 MOVIES 
SELECT  NB.NCONST,
        NB.PRIMARYNAME,
        TB.STARTYEAR,COUNT(*) AS MOVIES_COUNT
FROM sharmac.TITLE_PRINCIPALS  TP
INNER JOIN sharmac.TITLE_BASICS TB 
    ON TP.TCONST = tb.tconst
INNER JOIN  sharmac.NAME_BASICS NB
    ON NB.NCONST = tp.nconst
WHERE (TB.STARTYEAR BETWEEN '1926' AND '1930' ) AND (tb.titletype='movie') AND (tp.category = 'actress') 
GROUP BY NB.NCONST,NB.PRIMARYNAME , TB.STARTYEAR
HAVING COUNT(*)>3
ORDER BY COUNT(*) ASC,TB.STARTYEAR ASC,NB.PRIMARYNAME ASC
FETCH FIRST 1 ROWS ONLY;

--female last with 4 movies 
-- WE ARE JOING THE TABLES TITLE_PRINCIPALS,TITLE_BASICS, NAME_BASICS  WITH THE PARAMETERS BASED ON THE PRIMARY KEYS 
-- NOW WE ARE FITERING THE DATA BASED ON STARTYEAR BETWEEN '1926' AND '1930' titletype AS 'movie' FOR FEMALE
-- NOW WE COUNT BY GROUP IT BY NCONST THEN PRIMARY NAME AND THEN BY START YEAR 
-- SORT BY BY COUNT(*) ASC,TB.STARTYEAR DESC,NB.PRIMARYNAME desc
-- PRINT ONLY THE FIRST ROW
SELECT  NB.NCONST,
        NB.PRIMARYNAME,
        TB.STARTYEAR,COUNT(*) AS MOVIES_COUNT
FROM sharmac.TITLE_PRINCIPALS  TP
INNER JOIN sharmac.TITLE_BASICS TB 
    ON TP.TCONST = tb.tconst
INNER JOIN  sharmac.NAME_BASICS NB
    ON NB.NCONST = tp.nconst
WHERE (TB.STARTYEAR BETWEEN '1926' AND '1930') AND (tb.titletype='movie') AND (tp.category = 'actress') 
GROUP BY NB.NCONST,NB.PRIMARYNAME , TB.STARTYEAR
HAVING COUNT(*)>3
ORDER BY COUNT(*) ASC,TB.STARTYEAR DESC,NB.PRIMARYNAME desc
FETCH FIRST 1 ROWS ONLY;

set echo off;
spool off;